pr msg test

diff --git a/.github/workflows/pr-test.yml b/.github/workflows/pr-test.yml
--- a/.github/workflows/pr-test.yml
+++ b/.github/workflows/pr-test.yml
@@ -10,13 +10,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps: 
-    - name:  build step
-      id: build_id
-      run: |
-        echo " test-pr steps" 
-        exit 1
-    - uses: Dayanandachari/actions_repo@main
-      if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
+    # - name:  build step
+    #   id: build_id
+    #   run: |
+    #     echo " test-pr steps" 
+    #     exit 1
+    # - uses: Dayanandachari/actions_repo@main
+    #   if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
     
     # - name: Test
     #   uses: actions/github-script@0.3.0
@@ -45,7 +45,7 @@ jobs:
           curl \
           -X POST \
           -H "Accept: application/vnd.github+json" \
-          -H "Authorization: token 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" \
+          -H "Authorization: token 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" \
           https://api.github.com/repos/Dayanandachari/Github_action_repo/issues/5/comments \
           -d '{"body":"**Testing** 123"}'
       shell: bash
